name: Tests & coverage
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          args: --coverage-text
          php_version : 7.4
          version : 9
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage

      - name: PHPUnit tests for PHP 8
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          args: --coverage-text
          php_version: 8
          version: 9
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage

      - name: PHPUnit tests for PHP 8.1
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          args: --coverage-text
          php_version: 8.1
          version: 9
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "clover.xml"
          threshold_alert: 10
          threshold_warning: 50
